[input]
lef_files = ["inputs/ibex/Nangate45.lef"]
def_file = "inputs/ibex/ibex.def"
output_def = "output/ibex/placed.def"

[global_placement]
placer_max_iterations = 2000
convergence_threshold = 1e-4

[legalization]
algorithm = "abacus"
