[input]
bookshelf_aux_file = "inputs/ibm13/ibm13.aux"
output_def = "output/ibm13/placed.def"

[global_placement]
placer_max_iterations = 2000
convergence_threshold = 1e-4
electro_force_multiplier = 1000.0

[legalization]
algorithm = "abacus"
