//! A* Pathfinding Algorithm for Routing.
//!
//! Implements the A* algorithm with congestion-aware cost functions, guide
//! constraints, and layer-aware routing. Uses a sliding window to limit search
//! space and adaptive penalties for congestion and guide violations.

use crate::grid::RoutingGrid;
use eda_common::db::core::{LayerDirection, NetlistDB};
use eda_common::geom::coord::GridCoord;
use std::cmp::Ordering;
use std::collections::BinaryHeap;

/// State node in the A* search priority queue.
///
/// Stores the f-score (estimated total cost), g-score (actual cost from start),
/// and index into the routing window's local coordinate space. Nodes are
/// ordered by f-score (lowest first) to prioritize promising paths.
#[derive(Copy, Clone, Eq, PartialEq)]
struct State {
    f_score: i64,
    g_score: i64,
    index: u32,
}

impl Ord for State {
    /// Compares states for priority queue ordering.
    ///
    /// States are ordered by f-score (lowest first) to prioritize promising
    /// paths in A* search. Ties are broken by g-score to prefer paths with
    /// lower actual cost when estimated costs are equal.
    fn cmp(&self, other: &Self) -> Ordering {
        other
            .f_score
            .cmp(&self.f_score)
            .then_with(|| self.g_score.cmp(&other.g_score))
    }
}

impl PartialOrd for State {
    /// Partial comparison that always returns Some since State is totally ordered.
    ///
    /// Required by the Ord trait. Always delegates to cmp since State values
    /// can always be compared.
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

/// Trait for guide constraint checking during routing.
///
/// Allows routing algorithms to query whether a grid coordinate is within
/// the routing guide for the current net. Guides are generated by global
/// routing and constrain detailed routing to preferred regions.
pub trait GuideOracle {
    /// Returns true if the given coordinate is within the routing guide.
    fn is_in_guide(&self, c: GridCoord) -> bool;
}

/// Dummy guide oracle that allows routing anywhere.
///
/// Used as a fallback when guides are unavailable or when routing without
/// guide constraints. Always returns true to indicate all coordinates are
/// valid.
pub struct NoGuide;
impl GuideOracle for NoGuide {
    /// Always returns true to allow routing anywhere.
    ///
    /// Implements the GuideOracle trait for unconstrained routing scenarios.
    /// Used as a fallback when guides are unavailable or when routing without
    /// guide constraints.
    fn is_in_guide(&self, _c: GridCoord) -> bool {
        true
    }
}

/// A 3D bounding box that limits the A* search space.
///
/// Defines a rectangular window in X,Y with all layers included. Used to
/// reduce the search space by focusing on the region between start and end
/// points with a configurable margin. Provides methods to convert between
/// global grid coordinates and local window indices for efficient indexing.
#[derive(Clone, Copy)]
struct RoutingWindow {
    min_x: u32,
    max_x: u32,
    min_y: u32,
    max_y: u32,
    width: u32,
    height: u32,
    layers: u8,
}

impl RoutingWindow {
    /// Creates a new routing window from start/end points and margin.
    ///
    /// Computes the bounding box of all start points and the end point,
    /// then expands by the margin amount. Clamps to grid boundaries to
    /// ensure all coordinates are valid. The window includes all layers.
    fn new(
        starts: &[GridCoord],
        end: GridCoord,
        margin: u32,
        grid_w: u32,
        grid_h: u32,
        layers: u8,
    ) -> Self {
        let mut min_x = end.x;
        let mut max_x = end.x;
        let mut min_y = end.y;
        let mut max_y = end.y;
        for s in starts {
            min_x = min_x.min(s.x);
            max_x = max_x.max(s.x);
            min_y = min_y.min(s.y);
            max_y = max_y.max(s.y);
        }
        let min_x = min_x.saturating_sub(margin);
        let max_x = (max_x + margin).min(grid_w - 1);
        let min_y = min_y.saturating_sub(margin);
        let max_y = (max_y + margin).min(grid_h - 1);
        Self {
            min_x,
            max_x,
            min_y,
            max_y,
            width: max_x - min_x + 1,
            height: max_y - min_y + 1,
            layers,
        }
    }
    /// Checks if a grid coordinate is within this routing window.
    ///
    /// Returns true if the coordinate's X and Y are within the window bounds.
    /// Layer is not checked since the window includes all layers.
    #[inline(always)]
    fn contains(&self, c: GridCoord) -> bool {
        c.x >= self.min_x && c.x <= self.max_x && c.y >= self.min_y && c.y <= self.max_y
    }
    /// Converts a global grid coordinate to a local window index.
    ///
    /// Computes a linear index within the window's 3D space for efficient
    /// array access. The index encodes layer, Y, and X coordinates in that order.
    #[inline(always)]
    fn get_local_idx(&self, c: GridCoord) -> usize {
        let lx = c.x - self.min_x;
        let ly = c.y - self.min_y;
        let lz = c.z as u32;
        (lz * self.width * self.height + ly * self.width + lx) as usize
    }
    /// Converts a local window index back to a global grid coordinate.
    ///
    /// Decodes the linear index to extract layer, Y, and X coordinates,
    /// then converts back to global coordinates by adding window offsets.
    #[inline(always)]
    fn get_coord(&self, idx: u32) -> GridCoord {
        let plane_size = self.width * self.height;
        let z = (idx / plane_size) as u8;
        let rem = idx % plane_size;
        let y = rem / self.width + self.min_y;
        let x = rem % self.width + self.min_x;
        GridCoord::new(x, y, z)
    }
}

/// A* pathfinding solver with reusable state for multiple path queries.
///
/// Maintains search state (parent pointers, g-scores, visited tags) that
/// can be reused across multiple pathfinding queries to reduce allocation
/// overhead. Uses a tag-based visited tracking system to reset state
/// efficiently between queries without clearing large arrays.
#[derive(Clone)]
pub struct AStar {
    parents: Vec<u32>,
    g_score: Vec<i64>,
    visited_tag: Vec<u32>,
    current_tag: u32,
    capacity: usize,
}

impl AStar {
    /// Creates a new A* solver with default capacity.
    ///
    /// Allocates arrays for parent pointers, g-scores, and visited tags
    /// with initial capacity. The arrays will be expanded automatically
    /// if larger routing windows are encountered.
    pub fn new() -> Self {
        let cap = 100_000;
        Self {
            parents: vec![u32::MAX; cap],
            g_score: vec![i64::MAX; cap],
            visited_tag: vec![0; cap],
            current_tag: 1,
            capacity: cap,
        }
    }
    /// Ensures the internal arrays have sufficient capacity for the given size.
    ///
    /// Expands arrays by at least 2x when needed to reduce reallocation frequency.
    /// All new elements are initialized to default values (u32::MAX for parents,
    /// i64::MAX for g-scores, 0 for visited tags).
    fn ensure_capacity(&mut self, size: usize) {
        if size > self.capacity {
            self.capacity = size.max(self.capacity * 2);
            self.parents.resize(self.capacity, u32::MAX);
            self.g_score.resize(self.capacity, i64::MAX);
            self.visited_tag.resize(self.capacity, 0);
        }
    }
    /// Resets the visited tag for a new search window.
    ///
    /// Increments the current tag to invalidate all previous visited marks
    /// without clearing arrays. If the tag wraps around to 0, clears all
    /// visited tags explicitly to prevent false positives.
    fn reset_window(&mut self) {
        self.current_tag += 1;
        if self.current_tag == 0 {
            self.visited_tag.fill(0);
            self.current_tag = 1;
        }
    }

    /// Finds a path from any start coordinate to the end coordinate using A*.
    ///
    /// Searches the routing grid starting from any of the provided start
    /// coordinates, using A* with congestion-aware costs and guide constraints.
    /// The search is limited to a window around the start/end points to reduce
    /// search space. Returns the path as a sequence of grid coordinates, or
    /// None if no path exists within the expansion limit. The cost function
    /// penalizes congestion, guide violations, layer changes, and wrong-direction
    /// moves based on layer routing direction.
    pub fn find_path<G: RoutingGrid + ?Sized, O: GuideOracle>(
        &mut self,
        grid: &G,
        db: &NetlistDB,
        starts: &[GridCoord],
        end: GridCoord,
        collision_penalty: f64,
        heuristic_weight: f64,
        base_margin: u32,
        margin_multiplier: f64,
        oracle: &O,
        allowed_pins: &[GridCoord],
        max_expansions: u32,
        strict_mode: bool,
    ) -> Option<Vec<GridCoord>> {
        if starts.is_empty() {
            return None;
        }

        let window = RoutingWindow::new(
            starts,
            end,
            (base_margin as f64 * margin_multiplier) as u32,
            grid.width(),
            grid.height(),
            grid.layers(),
        );
        self.ensure_capacity((window.width * window.height * window.layers as u32) as usize);
        self.reset_window();

        let mut heap = BinaryHeap::new();
        let end_x = end.x as i32;
        let end_y = end.y as i32;
        let end_z = end.z as i32;
        let scale = 100.0;

        for &start in starts {
            if !window.contains(start) {
                continue;
            }
            let start_local = window.get_local_idx(start);
            self.g_score[start_local] = 0;
            self.visited_tag[start_local] = self.current_tag;
            self.parents[start_local] = u32::MAX;
            let h = self.heuristic(start, end_x, end_y, end_z, heuristic_weight);
            heap.push(State {
                f_score: (h * scale) as i64,
                g_score: 0,
                index: start_local as u32,
            });
        }

        let guide_penalty = (300.0 + collision_penalty * 0.5) * scale;
        let layer_change_cost = 8.0 * scale;
        let wrong_dir_cost = 15.0 * scale;
        let base_move_cost = 1.0 * scale;
        let mut expansions = 0;

        while let Some(State { f_score, index, .. }) = heap.pop() {
            let curr_local = index as usize;
            if f_score
                > self.g_score[curr_local]
                    + (self.heuristic_fast(index, &window, end_x, end_y, end_z, heuristic_weight)
                        * scale) as i64
            {
                continue;
            }
            let position = window.get_coord(index);
            if position == end {
                return Some(self.reconstruct_path(end, &window));
            }

            expansions += 1;
            if expansions > max_expansions {
                return None;
            }

            let current_g = self.g_score[curr_local];
            let mut neighbors = [GridCoord { x: 0, y: 0, z: 0 }; 6];
            let mut n_count = 0;
            if position.x > 0 {
                neighbors[n_count] = GridCoord::new(position.x - 1, position.y, position.z);
                n_count += 1;
            }
            if position.x < grid.width() - 1 {
                neighbors[n_count] = GridCoord::new(position.x + 1, position.y, position.z);
                n_count += 1;
            }
            if position.y > 0 {
                neighbors[n_count] = GridCoord::new(position.x, position.y - 1, position.z);
                n_count += 1;
            }
            if position.y < grid.height() - 1 {
                neighbors[n_count] = GridCoord::new(position.x, position.y + 1, position.z);
                n_count += 1;
            }
            if position.z > 0 {
                neighbors[n_count] = GridCoord::new(position.x, position.y, position.z - 1);
                n_count += 1;
            }
            if position.z < grid.layers() - 1 {
                neighbors[n_count] = GridCoord::new(position.x, position.y, position.z + 1);
                n_count += 1;
            }

            for i in 0..n_count {
                let neighbor = neighbors[i];
                if !window.contains(neighbor) {
                    continue;
                }

                if strict_mode && !oracle.is_in_guide(neighbor) && neighbor != end {
                    continue;
                }

                if grid.is_obstacle(neighbor) && neighbor != end {
                    let is_allowed = allowed_pins.iter().any(|&p| {
                        p == neighbor
                            || (p.z == neighbor.z
                                && ((p.x as i32 - neighbor.x as i32).abs()
                                    + (p.y as i32 - neighbor.y as i32).abs()
                                    <= 1))
                    });

                    if !is_allowed {
                        continue;
                    }
                }

                let is_pin = neighbor == end;
                let step_guide_cost = if is_pin || oracle.is_in_guide(neighbor) {
                    0.0
                } else {
                    guide_penalty
                };

                let dist_to_end =
                    (neighbor.x as i32 - end_x).abs() + (neighbor.y as i32 - end_y).abs();
                let is_near_pin = dist_to_end < 2;

                let mut step_move_cost = base_move_cost;
                if position.z != neighbor.z {
                    step_move_cost = layer_change_cost;
                    if position.z == 0 || neighbor.z == 0 {
                        step_move_cost = base_move_cost;
                    }
                } else if (position.z as usize) < db.layers.len() {
                    match db.layers[position.z as usize].direction {
                        LayerDirection::Vertical if position.x != neighbor.x => {
                            step_move_cost = if is_near_pin {
                                base_move_cost * 2.0
                            } else {
                                wrong_dir_cost
                            };
                        }
                        LayerDirection::Horizontal if position.y != neighbor.y => {
                            step_move_cost = if is_near_pin {
                                base_move_cost * 2.0
                            } else {
                                wrong_dir_cost
                            };
                        }
                        _ => {}
                    }
                }

                if position.z == 0 && neighbor.z == 0 {
                    step_move_cost += 800.0;
                }

                let node_cost = if neighbor == end {
                    0.0
                } else {
                    (grid.get_cost(neighbor, collision_penalty) - 1.0) * scale
                };
                let total_cost = step_move_cost + step_guide_cost + node_cost;
                let tentative_g = current_g + total_cost as i64;
                let neighbor_local = window.get_local_idx(neighbor);

                if self.visited_tag[neighbor_local] != self.current_tag
                    || tentative_g < self.g_score[neighbor_local]
                {
                    self.parents[neighbor_local] = curr_local as u32;
                    self.g_score[neighbor_local] = tentative_g;
                    self.visited_tag[neighbor_local] = self.current_tag;
                    let h = self.heuristic(neighbor, end_x, end_y, end_z, heuristic_weight);
                    heap.push(State {
                        f_score: tentative_g + (h * scale) as i64,
                        g_score: tentative_g,
                        index: neighbor_local as u32,
                    });
                }
            }
        }
        None
    }

    /// Computes the A* heuristic (estimated distance to goal).
    ///
    /// Uses Manhattan distance in X and Y, with layer changes weighted
    /// 5x more expensive to discourage unnecessary layer transitions.
    /// The weight parameter allows tuning the heuristic's influence on
    /// search behavior.
    #[inline(always)]
    fn heuristic(&self, a: GridCoord, ex: i32, ey: i32, ez: i32, weight: f64) -> f64 {
        ((a.x as i32 - ex).abs() as f64
            + (a.y as i32 - ey).abs() as f64
            + (a.z as i32 - ez).abs() as f64 * 5.0)
            * weight
    }
    /// Fast heuristic computation using window index instead of coordinate.
    ///
    /// Converts the window index to a coordinate first, then calls the
    /// main heuristic function. This avoids repeated coordinate conversions
    /// when the coordinate is already available as an index.
    #[inline(always)]
    fn heuristic_fast(
        &self,
        idx: u32,
        w: &RoutingWindow,
        ex: i32,
        ey: i32,
        ez: i32,
        weight: f64,
    ) -> f64 {
        self.heuristic(w.get_coord(idx), ex, ey, ez, weight)
    }
    /// Reconstructs the path from the end point back to the start.
    ///
    /// Follows parent pointers from the end coordinate back through the
    /// search tree until reaching a node with no parent (the start).
    /// Reverses the path to return it in start-to-end order.
    fn reconstruct_path(&self, end: GridCoord, window: &RoutingWindow) -> Vec<GridCoord> {
        let mut path = Vec::new();
        let mut curr_local = window.get_local_idx(end);
        loop {
            path.push(window.get_coord(curr_local as u32));
            let parent = self.parents[curr_local];
            if parent == u32::MAX {
                break;
            }
            curr_local = parent as usize;
        }
        path.reverse();
        path
    }
}
